name: sih22
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  antdesign_icons: ^0.0.3
  dio: ^4.0.6
  location: ^4.3.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.3
  fluster: ^1.2.0
  flutter_cache_manager: ^3.3.0
  custom_info_window: ^1.0.1
  clippy_flutter: ^2.0.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/building.png
    - assets/images/bgbuilding.png
    - assets/images/location.png
    - assets/images/text.png
    - assets/images/ndhm.png
    - assets/images/pin.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
